/*
* Copyright 2014 Dell Inc.
* ALL RIGHTS RESERVED.
*
* This software is the confidential and proprietary information of
* Dell Inc. ("Confidential Information").  You shall not
* disclose such Confidential Information and shall use it only in
* accordance with the terms of the license agreement you entered
* into with Dell Inc.
*
* DELL INC. MAKES NO REPRESENTATIONS OR WARRANTIES
* ABOUT THE SUITABILITY OF THE SOFTWARE, EITHER EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
* WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
* PARTICULAR PURPOSE, OR NON-INFRINGEMENT. DELL SHALL
* NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE
* AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
* THIS SOFTWARE OR ITS DERIVATIVES.
*/

package lab.sysu.prototype.apm.instrumentation;

public enum MethodId {
    EXECUTE_QUERY_WITH_SQL("executeQuery", "(Ljava/lang/String;)Ljava/sql/ResultSet;", "java.sql.ResultSet executeQuery(String sql) throws java.sql.SQLException {return super.executeQuery($1);}")
    , EXECUTE_UPDATE("executeUpdate", "(Ljava/lang/String;)I", "int executeUpdate(String sql) throws java.sql.SQLException {return super.executeUpdate($1);}")
    , EXECUTE_UPDATE_WITH_SIGNAL("executeUpdate", "(Ljava/lang/String;I)I", "int executeUpdate(String sql, int autoGeneratedKeys) throws java.sql.SQLException {return super.executeUpdate($1, $2);}")
    , EXECUTE_UPDATE_WITH_SIGNALS("executeUpdate", "(Ljava/lang/String;[I)I", "int executeUpdate(String sql, int columnIndexes[]) throws java.sql.SQLException {return super.executeUpdate($1, $2);}")
    , EXECUTE_UPDATE_WITH_SIGNALS_NAME("executeUpdate", "(Ljava/lang/String;[Ljava/lang/String;)I", "int executeUpdate(String sql, String columnNames[]) throws java.sql.SQLException {return super.executeUpdate($1, $2);}")
    , EXECUTE("execute", "(Ljava/lang/String;)Z", "boolean execute(String sql) throws java.sql.SQLException {return super.execute($1);}")
    , EXECUTE_WITH_SIGNAL("execute", "(Ljava/lang/String;I)Z", "boolean execute(String sql, int autoGeneratedKeys) throws java.sql.SQLException {return super.execute($1, $2);}")
    , EXECUTE_WITH_SIGNALS("execute", "(Ljava/lang/String;[I)Z", "boolean execute(String sql, int columnIndexes[]) throws java.sql.SQLException {return super.execute($1, $2);}")
    , EXECUTE_WITH_SIGNALS_NAME("execute", "(Ljava/lang/String;[Ljava/lang/String;)Z", "boolean execute(String sql, String columnNames[]) throws java.sql.SQLException {return super.execute($1, $2);}");


    private final String name;
    private final String signature;
    private final String shell;

    private MethodId(String name, String signature, String shell) {
        this.name = name;
        this.signature = signature;
        this.shell = shell;
    }

    public static MethodId findMethodId(String name, String signature) {

        for (MethodId methodId : MethodId.values()) {
            if (methodId.name.equals(name) && methodId.signature.equals(signature)) return methodId;
        }
        return null;
    }

    public String getSignature() {
        return signature;
    }


    public String getName() {
        return name;
    }

    @Override
    public String toString() {
        return new StringBuilder()
                .append(" ( ")
                .append(" name : " + name)
                .append(" signature : " + signature)
                .append(" ) ")
                .toString();
    }

    public String getShell() {
        return this.shell;
    }
}
